Config = {
    Debug = true,

    UntransferableItems = {
        ["donortoken1"] = true,
        ["donortoken2"] = true,
        ["card_writer"] = false,
        ["fraud_laptop"] = false,
        ["trapphone"] = false,
        ["5g_adapter"] = false,
        ["wifi_adapter"] = false,
        ["permission_slip"] = true,
        ["blackdiamond"] = true,
        -- ["wheel_spin_voucher"] = true,
    },

    TransferableItemsForJobs = {
        ["police"] = {
            ["blackdiamond"] = true,
            ["duffel"] = true,
            ["premium_duffel"] = true,
            ["pddonut"] = true,
        },
    },

    NonLootableJobs = {
        ["police"] = true,
        ["ambulance"] = true
    },

    Limits = {
        dead = {
            ['ammo-bb'] = { normal = 0, vip = 0 },
            ['ammo-10'] = { normal = 0, vip = 0 },
            ['ammo-22'] = { normal = 0, vip = 0 },
            ['ammo-38'] = { normal = 0, vip = 0 },
            ['ammo-44'] = { normal = 0, vip = 0 },
            ['ammo-45'] = { normal = 0, vip = 0 },
            ['ammo-50'] = { normal = 0, vip = 0 },
            ['ammo-9'] = { normal = 0, vip = 0 },
            ['ammo-rifle'] = { normal = 0, vip = 0 },
            ['ammo-rifle2'] = { normal = 0, vip = 0 },
            --Bankson WeaponPack Guns
            ['WEAPON_SWP2UZI'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2UGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TSCAR'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TG17S'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TEC9'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2RUGER'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2PG43XS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2P90'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2P22'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MPX'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MP5'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MCKGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2GR300BO'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G41CS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G23B'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G22S'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G21GC'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G19T'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G19CS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G18C'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G17MOSMH'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2DE'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BTANARP'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BLACKOUTAK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BG26'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BAGGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2B57'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2ARPBULLDOG'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2ARP3IN'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2AR15NS'] = { normal = 1, vip = 1 },
            -- Weapons
            ['WEAPON_CERAMICPISTOL'] = { normal = 1, vip = 1 },
            ['WEAPON_P210'] = { normal = 1, vip = 1 },
            ['WEAPON_T1911'] = { normal = 1, vip = 1 },
            ['WEAPON_DKFN502'] = { normal = 1, vip = 1 },
            ['WEAPON_PX4'] = { normal = 1, vip = 1 },
            ['WEAPON_MPSHIELDPLUS'] = { normal = 1, vip = 1 },
            ['WEAPON_SIGP238'] = { normal = 1, vip = 1 },
            ['WEAPON_FN57'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK41'] = { normal = 1, vip = 1 },
            ['WEAPON_TP9SF'] = { normal = 1, vip = 1 },
            ['WEAPON_SR40'] = { normal = 1, vip = 1 },
            ['WEAPON_P30L'] = { normal = 1, vip = 1 },
            ['WEAPON_G17B'] = { normal = 1, vip = 1 },
            ['WEAPON_G19XD'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK45'] = { normal = 1, vip = 1 },
            ['WEAPON_ILLGLOCK17'] = { normal = 1, vip = 1 },
            ['WEAPON_TGLOCK45'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK22'] = { normal = 1, vip = 1 },
            ['WEAPON_MP10MM'] = { normal = 1, vip = 1 },
            ['WEAPON_BERETTAM9'] = { normal = 1, vip = 1 },
            ['WEAPON_TAURUSGX4'] = { normal = 1, vip = 1 },
            ['WEAPON_DKXD9'] = { normal = 1, vip = 1 },
            ['WEAPON_DKSIGP320'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK18'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCKDEMON'] = { normal = 1, vip = 1 },
            ['WEAPON_TEC9S'] = { normal = 1, vip = 1 },
            ['WEAPON_10INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_4INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_LILARP'] = { normal = 1, vip = 1 },
            ['WEAPON_GHOST17'] = { normal = 1, vip = 1 },
            ['WEAPON_DKGLOCK26SUB'] = { normal = 1, vip = 1 },
            ['WEAPON_BSCAR'] = { normal = 1, vip = 1 },
            ['WEAPON_DAR15'] = { normal = 1, vip = 1 },
            ['WEAPON_MICROMP5'] = { normal = 1, vip = 1 },
            ['WEAPON_SUB2000'] = { normal = 1, vip = 1 },
            ['WEAPON_RAM9D'] = { normal = 1, vip = 1 },
            ['WEAPON_MAC4A1'] = { normal = 1, vip = 1 },
            ['WEAPON_BLUEGLOCKS'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK22S'] = { normal = 1, vip = 1 },
            ['WEAPON_MINIAK47'] = { normal = 1, vip = 1 },
            ['WEAPON_KRISSVECTOR'] = { normal = 1, vip = 1 },
            ['WEAPON_BLACKARP'] = { normal = 1, vip = 1 },
            ['WEAPON_TARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDAUG'] = { normal = 1, vip = 1 },
            ['WEAPON_BAR15'] = { normal = 1, vip = 1 },
            ['WEAPON_RAM7K'] = { normal = 1, vip = 1 },
            ['WEAPON_CENTURYMICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_INCOGNITOG26'] = { normal = 1, vip = 1 },
            ['WEAPON_ILLGLOCK19X'] = { normal = 1, vip = 1 },
            ['WEAPON_G41GEN4'] = { normal = 1, vip = 1 },
            ['WEAPON_G17GB'] = { normal = 1, vip = 1 },
            ['WEAPON_GREYARP'] = { normal = 1, vip = 1 },
            ['WEAPON_DKDDM4V7'] = { normal = 1, vip = 1 },
            ['WEAPON_SIGSPEAR'] = { normal = 1, vip = 1 },
            ['WEAPON_MICROMCX'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK21'] = { normal = 1, vip = 1 },
            ['WEAPON_MGGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_APS'] = { normal = 1, vip = 1 },
            ['WEAPON_RDP'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK26S'] = { normal = 1, vip = 1 },
            ['WEAPON_MICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MPX'] = { normal = 1, vip = 1 },
            ['WEAPON_ZIPTIE'] = { normal = 1, vip = 1 },
            ['WEAPON_G22GEN4'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK19S'] = { normal = 1, vip = 1 },
            ['WEAPON_XDME'] = { normal = 1, vip = 1 },
            --Pink Guns
            ['WEAPON_PINKM18'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKM45A1'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKSWMP9'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKGLOCK21'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKP80'] = { normal = 1, vip = 1 },
            ['WEAPON_ARP9'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKARP'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKDRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMINIDRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MP5'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMP7'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKSTRAPARP'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMPA30'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKARPISTOL'] = { normal = 1, vip = 1 },
            --AUTO PISTOLS
            ['WEAPON_DKGLOCK20'] = { normal = 1, vip = 1 },
            ['WEAPON_G17G5MOS'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCKBEAMS'] = { normal = 1, vip = 1 },
            ['WEAPON_PFC9'] = { normal = 1, vip = 1 },
            ['WEAPON_DKGLOCK34'] = { normal = 1, vip = 1 },
            ['WEAPON_GEN5STEELBUTTON'] = { normal = 1, vip = 1 },
            ['WEAPON_MIDASGLOCK'] = { normal = 1, vip = 1 },
            --LESS ATTACHMENT ARS
            ['WEAPON_ARCQB'] = { normal = 1, vip = 1 },
            ['WEAPON_DDM4ARP'] = { normal = 1, vip = 1 },
            ['WEAPON_THOMPSON'] = { normal = 1, vip = 1 },
            ['WEAPON_CADRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MAC10'] = { normal = 1, vip = 1 },
            ['WEAPON_CAMICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_ARMAC'] = { normal = 1, vip = 1 },
            ['WEAPON_BLUEARP'] = { normal = 1, vip = 1 },
            ['WEAPON_WOARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDM4A1'] = { normal = 1, vip = 1 },
            --MORE ATTACHMENT ARS
            ['WEAPON_MICROREDARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDARP'] = { normal = 1, vip = 1 },
            ['WEAPON_8INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_DMK18'] = { normal = 1, vip = 1 },
            ['WEAPON_SPEAR'] = { normal = 1, vip = 1 },
            ['WEAPON_DKMK47'] = { normal = 1, vip = 1 },
            ['WEAPON_M231'] = { normal = 1, vip = 1 },
            ['WEAPON_GHMICROARP'] = { normal = 1, vip = 1 },
            --Weapon Basic Bundle
            ['WEAPON_ARPISTOL'] = { normal = 1, vip = 1 },
            ['WEAPON_XDS9'] = { normal = 1, vip = 1 },
            ['WEAPON_PPK'] = { normal = 1, vip = 1 },
            ['WEAPON_PPS'] = { normal = 1, vip = 1 },
            ['WEAPON_DDM4V5'] = { normal = 1, vip = 1 },
            ['WEAPON_DAGGER'] = { normal = 1, vip = 1 },
            ['WEAPON_MACHETE'] = { normal = 1, vip = 1 },
            ['WEAPON_BARP'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK18C'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK40S'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK40'] = { normal = 1, vip = 1 },
            ['WEAPON_RUGER57'] = { normal = 1, vip = 1 },
            --Coin Shop
            ['WEAPON_ARC15_MINI'] = { normal = 1, vip = 1 },
            ['WEAPON_AUTOSMG'] = { normal = 1, vip = 1 },
            ['WEAPON_BABYSKORP'] = { normal = 1, vip = 1 },
            ['WEAPON_BULLPUP_SMG_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_CASR'] = { normal = 1, vip = 1 },
            ['WEAPON_IDW'] = { normal = 1, vip = 1 },
            ['WEAPON_M4A1_CHROMIUM'] = { normal = 1, vip = 1 },
            ['WEAPON_M270D_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_MP7_CHROMIUM'] = { normal = 1, vip = 1 },
            ['WEAPON_AK_SHORTSTOCK_CHR'] = { normal = 1, vip = 1 },
            ['WEAPON_SPX_7_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWTICH17'] = { normal = 1, vip = 1 },
            ['WEAPON_GOLDDRAC']   = { normal = 1, vip = 1 },
            ['WEAPON_AK_47_GOLD'] = { normal = 1, vip = 1 },
            ['WEAPON_HFAP']       = { normal = 1, vip = 1 },
            ['WEAPON_TPM9']       = { normal = 1, vip = 1 },
            ['WEAPON_SWP2HATCHET'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2KNIFE']       = { normal = 1, vip = 1 },
            ['WEAPON_SWP2NFBAT']       = { normal = 1, vip = 1 },
            -- Attachments
            ['at_clip_akdrum'] = { normal = 1, vip = 1 },
            ['at_stacked_mag_rifle'] = { normal = 1, vip = 1 },
            ['at_clip_ardrum'] = { normal = 1, vip = 1 },
            ['at_clip_seethrough_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_vector_mag'] = { normal = 1, vip = 1 },
            ['at_laser'] = { normal = 1, vip = 1 },
            ['at_pistol_sight'] = { normal = 1, vip = 1 },
            ['at_pistol_suppressor'] = { normal = 1, vip = 1 },
            ['at_rifle_suppressor'] = { normal = 1, vip = 1 },
            ['at_clip_100_rifle'] = { normal = 1, vip = 1 },
            ['at_flashlight'] = { normal = 1, vip = 1 },
            ['at_suppressor_light'] = { normal = 1, vip = 1 },
            ['at_grip'] = { normal = 1, vip = 1 },
            ['at_clip_extended_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_extended_rifle'] = { normal = 1, vip = 1 },
            ['at_clip_extended_shotgun'] = { normal = 1, vip = 1 },
            ['at_clip_drum_rifle'] = { normal = 1, vip = 1 },
            ['at_scope_medium'] = { normal = 1, vip = 1 },
            ['at_clip_drum_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_extended_smg'] = { normal = 1, vip = 1 },
            ['at_clip_100_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_clear'] = { normal = 1, vip = 1 },
            ['at_clip_drum_smg'] = { normal = 1, vip = 1 },
            ['at_clip_drum_shotgun'] = { normal = 1, vip = 1 },
            --Drugs
            ['cannabis'] = { normal = 1000, vip = 10000 },
            ['coke_brick'] = { normal = 1000, vip = 10000 },
            ['coke_bag'] = { normal = 1000, vip = 10000 },
            ['liquid_ketamine'] = { normal = 1000, vip = 10000 },
            ['bagged_spice'] = { normal = 1000, vip = 10000 },
            ['xanax_bar'] = { normal = 1000, vip = 10000 },
            ['xanax_bag'] = { normal = 1000, vip = 10000 },
            ['meth_packaged'] = { normal = 1000, vip = 10000 },
            ['meth_pure'] = { normal = 1000, vip = 10000 },
            ['ketamine'] = { normal = 1000, vip = 10000 },
            ['lean_cup'] = { normal = 1000, vip = 10000 },
            ['dirty_sprite'] = { normal = 1000, vip = 10000 },
            ['spice'] = { normal = 1000, vip = 10000 },
            ['tusi'] = { normal = 1000, vip = 10000 },
            ['benzodope'] = { normal = 1000, vip = 10000 },
            ['tusi_brick'] = { normal = 1000, vip = 10000 },
            ['lsd_tab'] = { normal = 1000, vip = 10000 },
            ['fentanyl'] = { normal = 1000, vip = 10000 },
            ['xanax_pill'] = { normal = 1000, vip = 10000 },
            ['psy_bloom'] = { normal = 1000, vip = 10000 },
            --Money
            ['black_money'] = { normal = 1000000, vip = 2000000 },
        },

        handsup = {
            ['blackdiamond'] = { normal = 0, vip = 0 },
            ['ammo-10'] = { normal = 100, vip = 100 },
            ['ammo-22'] = { normal = 100, vip = 100 },
            ['ammo-38'] = { normal = 100, vip = 100 },
            ['ammo-44'] = { normal = 100, vip = 100 },
            ['ammo-45'] = { normal = 100, vip = 100 },
            ['ammo-50'] = { normal = 100, vip = 100 },
            ['ammo-9'] = { normal = 100, vip = 100 },
            ['ammo-rifle'] = { normal = 100, vip = 100 },
            ['ammo-rifle2'] = { normal = 100, vip = 100 },
            --COINGUNS
            ['WEAPON_BULLPUP_SMG_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_CASR'] = { normal = 1, vip = 1 },
            ['WEAPON_IDW'] = { normal = 1, vip = 1 },
            ['WEAPON_M270D_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_ARC15_MINI'] = { normal = 1, vip = 1 },
            ['WEAPON_AUTOSMG'] = { normal = 1, vip = 1 },
            ['WEAPON_M4A1_CHROMIUM'] = { normal = 1, vip = 1 },
            ['WEAPON_MP7_CHROMIUM'] = { normal = 1, vip = 1 },
            ['WEAPON_AK_SHORTSTOCK_CHR'] = { normal = 1, vip = 1 },
            ['WEAPON_SPX_7_VVS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWTICH17'] = { normal = 1, vip = 1 },
            ['WEAPON_BABYSKORP'] = { normal = 1, vip = 1 },
            --Bankson WeaponPack Guns
            ['WEAPON_SWP2UZI'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2UGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TSCAR'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TG17S'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2TEC9'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2RUGER'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2PG43XS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2P90'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2P22'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MPX'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MP5'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2MCKGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2GR300BO'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G41CS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G23B'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G22S'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G21GC'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G19T'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G19CS'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G18C'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2G17MOSMH'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2DE'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BTANARP'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BLACKOUTAK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BG26'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2BAGGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2B57'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2ARPBULLDOG'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2ARP3IN'] = { normal = 1, vip = 1 },
            ['WEAPON_SWP2AR15NS'] = { normal = 1, vip = 1 },
            -- Weapons
            ['WEAPON_CERAMICPISTOL'] = { normal = 1, vip = 1 },
            ['WEAPON_DAGGER'] = { normal = 1, vip = 1 },
            ['WEAPON_P210'] = { normal = 1, vip = 1 },
            ['WEAPON_T1911'] = { normal = 1, vip = 1 },
            ['WEAPON_DKFN502'] = { normal = 1, vip = 1 },
            ['WEAPON_PX4'] = { normal = 1, vip = 1 },
            ['WEAPON_MPSHIELDPLUS'] = { normal = 1, vip = 1 },
            ['WEAPON_SIGP238'] = { normal = 1, vip = 1 },
            ['WEAPON_FN57'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK41'] = { normal = 1, vip = 1 },
            ['WEAPON_TP9SF'] = { normal = 1, vip = 1 },
            ['WEAPON_SR40'] = { normal = 1, vip = 1 },
            ['WEAPON_P30L'] = { normal = 1, vip = 1 },
            ['WEAPON_G17B'] = { normal = 1, vip = 1 },
            ['WEAPON_G19XD'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK45'] = { normal = 1, vip = 1 },
            ['WEAPON_ILLGLOCK17'] = { normal = 1, vip = 1 },
            ['WEAPON_TGLOCK45'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK22'] = { normal = 1, vip = 1 },
            ['WEAPON_MP10MM'] = { normal = 1, vip = 1 },
            ['WEAPON_BERETTAM9'] = { normal = 1, vip = 1 },
            ['WEAPON_G22GEN4'] = { normal = 1, vip = 1 },
            ['WEAPON_TAURUSGX4'] = { normal = 1, vip = 1 },
            ['WEAPON_DKXD9'] = { normal = 1, vip = 1 },
            ['WEAPON_DKSIGP320'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK18'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCKDEMON'] = { normal = 1, vip = 1 },
            ['WEAPON_TEC9S'] = { normal = 1, vip = 1 },
            ['WEAPON_10INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_4INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_LILARP'] = { normal = 1, vip = 1 },
            ['WEAPON_GHOST17'] = { normal = 1, vip = 1 },
            ['WEAPON_DKGLOCK26SUB'] = { normal = 1, vip = 1 },
            ['WEAPON_BSCAR'] = { normal = 1, vip = 1 },
            ['WEAPON_DAR15'] = { normal = 1, vip = 1 },
            ['WEAPON_MICROMP5'] = { normal = 1, vip = 1 },
            ['WEAPON_SUB2000'] = { normal = 1, vip = 1 },
            ['WEAPON_RAM9D'] = { normal = 1, vip = 1 },
            ['WEAPON_MAC4A1'] = { normal = 1, vip = 1 },
            ['WEAPON_BLUEGLOCKS'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK22S'] = { normal = 1, vip = 1 },
            ['WEAPON_MINIAK47'] = { normal = 1, vip = 1 },
            ['WEAPON_KRISSVECTOR'] = { normal = 1, vip = 1 },
            ['WEAPON_BLACKARP'] = { normal = 1, vip = 1 },
            ['WEAPON_TARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDAUG'] = { normal = 1, vip = 1 },
            ['WEAPON_BAR15'] = { normal = 1, vip = 1 },
            ['WEAPON_RAM7K'] = { normal = 1, vip = 1 },
            ['WEAPON_CENTURYMICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_INCOGNITOG26'] = { normal = 1, vip = 1 },
            ['WEAPON_ILLGLOCK19X'] = { normal = 1, vip = 1 },
            ['WEAPON_G41GEN4'] = { normal = 1, vip = 1 },
            ['WEAPON_G17GB'] = { normal = 1, vip = 1 },
            ['WEAPON_GREYARP'] = { normal = 1, vip = 1 },
            ['WEAPON_DKDDM4V7'] = { normal = 1, vip = 1 },
            ['WEAPON_SIGSPEAR'] = { normal = 1, vip = 1 },
            ['WEAPON_MICROMCX'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK21'] = { normal = 1, vip = 1 },
            ['WEAPON_MGGLOCK'] = { normal = 1, vip = 1 },
            ['WEAPON_DKFN502'] = { normal = 1, vip = 1 },
            ['WEAPON_APS'] = { normal = 1, vip = 1 },
            ['WEAPON_RDP'] = { normal = 1, vip = 1 },
            ['WEAPON_BLUEARP'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCK26S'] = { normal = 1, vip = 1 },
            ['WEAPON_MICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MPX'] = { normal = 1, vip = 1 },
            ['WEAPON_ZIPTIE'] = { normal = 1, vip = 1 },
            ['WEAPON_MIDASGLOCK'] = { normal = 1, vip = 1 },
            --AUTO PISTOLS
            ['WEAPON_DKGLOCK20'] = { normal = 1, vip = 1 },
            ['WEAPON_G17G5MOS'] = { normal = 1, vip = 1 },
            ['WEAPON_GLOCKBEAMS'] = { normal = 1, vip = 1 },
            ['WEAPON_PFC9'] = { normal = 1, vip = 1 },
            ['WEAPON_DKGLOCK34'] = { normal = 1, vip = 1 },
            ['WEAPON_GEN5STEELBUTTON'] = { normal = 1, vip = 1 },
            --LESS ATTACHMENT ARS
            ['WEAPON_ARCQB'] = { normal = 1, vip = 1 },
            ['WEAPON_DDM4ARP'] = { normal = 1, vip = 1 },
            ['WEAPON_THOMPSON'] = { normal = 1, vip = 1 },
            ['WEAPON_CADRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MAC10'] = { normal = 1, vip = 1 },
            ['WEAPON_CAMICRODRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_ARMAC'] = { normal = 1, vip = 1 },
            ['WEAPON_WOARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDM4A1'] = { normal = 1, vip = 1 },
            --MORE ATTACHMENT ARS
            ['WEAPON_MICROREDARP'] = { normal = 1, vip = 1 },
            ['WEAPON_REDARP'] = { normal = 1, vip = 1 },
            ['WEAPON_8INCHARP'] = { normal = 1, vip = 1 },
            ['WEAPON_DMK18'] = { normal = 1, vip = 1 },
            ['WEAPON_SPEAR'] = { normal = 1, vip = 1 },
            ['WEAPON_DKMK47'] = { normal = 1, vip = 1 },
            ['WEAPON_M231'] = { normal = 1, vip = 1 },
            ['WEAPON_GHMICROARP'] = { normal = 1, vip = 1 },
            --Pink Guns
            ['WEAPON_PINKM18'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKM45A1'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKSWMP9'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKGLOCK21'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKP80'] = { normal = 1, vip = 1 },
            ['WEAPON_ARP9'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKARP'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKDRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMINIDRACO'] = { normal = 1, vip = 1 },
            ['WEAPON_MP5'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMP7'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKSTRAPARP'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKMPA30'] = { normal = 1, vip = 1 },
            ['WEAPON_PINKARPISTOL'] = { normal = 1, vip = 1 },
            --Weapon Basic Bundle
            ['WEAPON_ARPISTOL'] = { normal = 1, vip = 1 },
            ['WEAPON_XDS9'] = { normal = 1, vip = 1 },
            ['WEAPON_PPK'] = { normal = 1, vip = 1 },
            ['WEAPON_PPS'] = { normal = 1, vip = 1 },
            -- Attachments
            ['at_clip_akdrum'] = { normal = 1, vip = 1 },
            ['at_stacked_mag_rifle'] = { normal = 1, vip = 1 },
            ['at_clip_ardrum'] = { normal = 1, vip = 1 },
            ['at_clip_seethrough_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_vector_mag'] = { normal = 1, vip = 1 },
            ['at_laser'] = { normal = 1, vip = 1 },
            ['at_pistol_sight'] = { normal = 1, vip = 1 },
            ['at_pistol_suppressor'] = { normal = 1, vip = 1 },
            ['at_rifle_suppressor'] = { normal = 1, vip = 1 },
            ['at_clip_100_rifle'] = { normal = 1, vip = 1 },
            ['at_flashlight'] = { normal = 1, vip = 1 },
            ['at_suppressor_light'] = { normal = 1, vip = 1 },
            ['at_grip'] = { normal = 1, vip = 1 },
            ['at_clip_extended_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_extended_rifle'] = { normal = 1, vip = 1 },
            ['at_clip_extended_shotgun'] = { normal = 1, vip = 1 },
            ['at_clip_drum_rifle'] = { normal = 1, vip = 1 },
            ['at_scope_medium'] = { normal = 1, vip = 1 },
            ['at_clip_drum_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_extended_smg'] = { normal = 1, vip = 1 },
            ['at_clip_100_pistol'] = { normal = 1, vip = 1 },
            ['at_clip_clear'] = { normal = 1, vip = 1 },
            ['at_clip_drum_smg'] = { normal = 1, vip = 1 },
            ['at_clip_drum_shotgun'] = { normal = 1, vip = 1 },
            --Drugs
            ['cannabis'] = { normal = 1000, vip = 10000 },
            ['coke_brick'] = { normal = 1000, vip = 10000 },
            ['coke_bag'] = { normal = 1000, vip = 10000 },
            ['liquid_ketamine'] = { normal = 1000, vip = 10000 },
            ['bagged_spice'] = { normal = 1000, vip = 10000 },
            ['xanax_bar'] = { normal = 1000, vip = 10000 },
            ['xanax_bag'] = { normal = 1000, vip = 10000 },
            ['meth_packaged'] = { normal = 1000, vip = 10000 },
            ['meth_pure'] = { normal = 1000, vip = 10000 },
            ['ketamine'] = { normal = 1000, vip = 10000 },
            ['lean_cup'] = { normal = 1000, vip = 10000 },
            ['dirty_sprite'] = { normal = 1000, vip = 10000 },
            ['spice'] = { normal = 1000, vip = 10000 },
            ['tusi'] = { normal = 1000, vip = 10000 },
            ['benzodope'] = { normal = 1000, vip = 10000 },
            ['tusi_brick'] = { normal = 1000, vip = 10000 },
            ['lsd_tab'] = { normal = 1000, vip = 10000 },
            ['fentanyl'] = { normal = 1000, vip = 10000 },
            ['xanax_pill'] = { normal = 1000, vip = 10000 },
            ['psy_bloom'] = { normal = 1000, vip = 10000 },
            --Money
            ['black_money'] = { normal = 1000000, vip = 2000000 },
            --Misc Items
            ['phone'] = { normal = 1, vip = 1 },
            ['washing_blue_card'] = { normal = 1, vip = 1 },
            ['washing_yellow_card'] = { normal = 1, vip = 1 },
            ['washing_green_card'] = { normal = 1, vip = 1 },
            ['washing_red_card'] = { normal = 1, vip = 1 },
            ['armour'] = { normal = 10, vip = 20 },
        },

        glovebox = {
            ['money'] = { normal = 250000, vip = 250000 },
            ['black_money'] = { normal = 500000, vip = 1000000 },
        },

        stash = {
            ['money'] = { normal = 1000000, vip = 1000000 },
            ['black_money'] = { normal = 1000000, vip = 2000000 },
        },

        trunk = {
            ['money'] = { normal = 500000, vip = 500000 },
            ['black_money'] = { normal = 1000000, vip = 1500000 },
        },

        duffle = {
            ['money'] = { normal = 500000, vip = 500000 },
            ['black_money'] = { normal = 750000, vip = 750000 },
        }
    },

    DuffleBlacklist = {
        ['weapon_rpg'] = true,
        ['weapon_railgun'] = true,
        ['weapon_minigun'] = true,
        ['gold'] = true,
        ['evidence'] = true,
        ['police_radio'] = true,
    }
}
